"""Change event_id to Integer and add index

Revision ID: 5dbb1b482dee
Revises: 
Create Date: 2025-03-04 01:08:04.934916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dbb1b482dee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('bet_id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the bet'),
    sa.Column('event_id', sa.Integer(), nullable=False, comment='ID of the event this bet is placed on'),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='Monetary amount of the bet (with 2 decimal places)'),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', name='betstatus'), nullable=False, comment='Current status of the bet (PENDING, WON, LOST)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Timestamp when the bet was created'),
    sa.PrimaryKeyConstraint('bet_id', name=op.f('pk_bet'))
    )
    op.create_index(op.f('ix_bet_event_id'), 'bet', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bet_event_id'), table_name='bet')
    op.drop_table('bet')
    # ### end Alembic commands ###
